### ISSUE TITLE
Fix URL’s in triggers

### ISSUE THREAD

**Issue by MantasTumenas** [MantasTumenas/Zabbix-template-for-Microsoft-SQL-Server#1]
Fix URL’s in triggers prototypes. Microsoft updated their URLs and current links leads to a page 404.

**Comment by SergeBrick** [comment]
Indeed. Example
Instead 
https://docs.microsoft.com/en-us/sql/2014/relational-databases/performance-monitor/sql-server-locks-object?view=sql-server-2016
Need to
https://docs.microsoft.com/en-us/sql/relational-databases/performance-monitor/sql-server-locks-object?view=sql-server-2016

**Comment by MantasTumenas** [comment]
Fixed and uploaded.
