### ISSUE TITLE
Value "Error executing query on !" of type "string" is not suitable for value type "Numeric (unsigned)"

### ISSUE THREAD

**Issue by mksplmax** [MantasTumenas/Zabbix-template-for-Microsoft-SQL-Server#10]
Hi

Thanks for template.

Template with discovery.
sql 2014

SQL Server Databases Discovery
database.mssql.status 
Value "Error executing query on !" of type "string" is not suitable for value type "Numeric (unsigned)"
Can you help with this?

Thanks

**Comment by MantasTumenas** [comment]
Value "Error executing query on !" means you are getting some kind of error
- "cannot execute query", "cannot read database status" (therefore
"string"). You should get integer ("Numeric"). Probable reason - not enough
rights to execute database status script. For precise error text, execute
database status script, directly in sql server within a Zabbix agent
service login rights

**Comment by mksplmax** [comment]
Hi.
Thanks for help
It all worked
But one more question - if you know what status 31 means?
Thanks

**Comment by MantasTumenas** [comment]
Hi.
From value mapping. 31 means database is in AlwaysOn, Synchronized. Have
you imported value mappings?

**Comment by mksplmax** [comment]
Thanks...Yes. But i see only from 1 to 10....
[Zabbix Value Mapping.zip](https://github.com/MantasTumenas/Zabbix-template-for-Microsoft-SQL-Server/files/2986984/Zabbix.Value.Mapping.zip)

**Comment by mksplmax** [comment]
deleted the value and imported again - everything became ok. ...Thank

**Comment by MantasTumenas** [comment]
Good to hear it. Good luck

**Comment by MantasTumenas** [comment]
Hello,
Have you tried this solution yet?
https://github.com/MantasTumenas/Zabbix-template-for-Microsoft-SQL-Server/issues/10
In short - zabbix agent service account does not have enough rights in sql
server. Rights needed are described in manual or you can try a shortcut and
assigned sysadmin rights

**Comment by MantasTumenas** [comment]
sorry, wrong recipient. do not pay attention.
mantas
