### ISSUE TITLE
what is different between with and without SQL instance discovery

### ISSUE THREAD

**Issue by wangjiangptt** [MantasTumenas/Zabbix-template-for-Microsoft-SQL-Server#12]
what is different between with and without SQL instance discovery

**Comment by MantasTumenas** [comment]
With SQL instance discovery - scripts discover every instance, every
database and applies templates (items, triggers).
Without SQL instance discovery - you have to manually define instance and
database names, which you want to monitor.

The choiCe depends on your current situation. If you are responsible and
have full control over all the instances and databases (as in a database
admin for the company), you should go with discovery script.
If you are responsible only for a part of SQL server (1 database or
instance) you can go without discovery. For example, you have to support
external company, which asks, for your help only for 1 database and nothing
more. Or you have to look over DEV server in your company, there developers
are also a sysadmins and do anything they want (Shutdown SQL Agent, take
dev database offline and so on). In last case I would monitor only instance
and system databases.

To keep in mind - I am planning to ditch a template "Without SQL instance
discovery" and instead improve a template "With SQL instance discovery".
Improved template will have an option to select instances or databases, in
case you need to monitor only part of SQL server

**Comment by MantasTumenas** [comment]
Also. for a template with instance discovery to work, the powershell 3.0 or higher must be installed. It comes by default on WinOS 2012 or higher.
Had a case, there I had to monitor SQL 2000 on older WinOS and could not install powershell 3.0. Had to to use highly modified template without instance discovery.
