### ISSUE TITLE
Only one PS process

### ISSUE THREAD

**Issue by t2client** [MantasTumenas/Zabbix-template-for-Microsoft-SQL-Server#15]
Hello,

I posted here https://www.zabbix.com/forum/em-portugues-y-en-espanol/380401-lentitud-en-zabbix-agent-active-sql-server-y-powershell (sorry, in Spanish) a problem related with Zabbix or PowerShell configuration.
The problem resides in there are a lot of items queued in Zabbix Server, all of them related with Active items about this template. I checked on the server, only one PowerShell.exe process is running at a time. Each PowerShell query spends 5 seconds more or less but we have 4 instances in one server with 20 databases, and the information never is up to date.

In the graph of the post you can see how often I have data, in this example, status database.

I appreciate your comments.

Regards,

**Comment by MantasTumenas** [comment]
Hello,
"there are a lot of items queued in Zabbix Server" - first guess -
incorrectly configured zabbix agent and/or firewall and Item (Active) is
not supported. Have you tested other items with active type? does it work?
Mantas

**Comment by t2client** [comment]
Hello,

Other Active items are working properly, like _Template Windows OS_ items.

Here you are the zabbix_agentd.conf file.

```
LogType=file
LogFile=C:\Program Files\Zabbix Agent\Log\zabbix_agentd.log
LogFileSize=1
DebugLevel=3
EnableRemoteCommands=1
LogRemoteCommands=1
ListenPort=10050
Hostname=sqlserver.local
Include=C:\Program Files\Zabbix Agent\conf.d\*.conf
Server=zabbix.local
ServerActive=zabbix.local
UnsafeUserParameters=1
Timeout=30
```

**Comment by MantasTumenas** [comment]
Ok, lets localize the problem. Template is working, because the discovery is working, the items are discovered and queried by zabbix server from zabbix agent. They simply do not carry info from host to zabbix - they stuck in queue. 
"Other Active items are working properly, like Template Windows OS items" - can you show me the configuration of the active item, which is working and receiving data?

**Comment by t2client** [comment]
Apologies, Template Window OS times aren't active 😔 
but, I checked this issue: https://support.zabbix.com/browse/ZBXNEXT-691

> 2. Only one thread (process) deal with active checks. Can cause significant delays.

We will modify the template to use "Zabbix Agent" instead "Zabbix Agent (active)" type.

**Comment by MantasTumenas** [comment]
"Apologies, Template Window OS times aren't active " - I knew it :)
Feel free to modify according to your needs. But be aware that some items works only in Active type. Eventlog comes to mind first. Let me know if your issue went away.
