### ISSUE TITLE
Issue with the multi-instance discovery rules

### ISSUE THREAD

**Issue by ioannis-pan** [MantasTumenas/Zabbix-template-for-Microsoft-SQL-Server#16]
I am having trouble with your template, the template works fine when there is one instance (using the multi-instance template) but when there are more than one instances the discovery rules doesn't working at all. The scripts seems working fine and the "zabbix_get" on zabbix server receiving the data but the item prototypes never become items. What possible is going wrong?

**Comment by MantasTumenas** [comment]
I need zabbix agent log, zabbix conf file, user parameters file and printscreen, from host discovery tabs and host items tabs

**Comment by ioannis-pan** [comment]
Ok i am attaching you everything that i can to upload:
Tell me if you need anything else:

<img width="706" alt="cap1" src="https://user-images.githubusercontent.com/51368583/59662335-63bdc500-91b5-11e9-86e0-1c3b84d1ddb1.png">
<img width="599" alt="cap2" src="https://user-images.githubusercontent.com/51368583/59662342-66b8b580-91b5-11e9-8ed2-ae2d25db7dea.png">
<img width="600" alt="cap3" src="https://user-images.githubusercontent.com/51368583/59662352-6a4c3c80-91b5-11e9-93c8-d8b24b3c03d2.png">
![cap4](https://user-images.githubusercontent.com/51368583/59662360-6fa98700-91b5-11e9-8656-fa07fc919631.png)
![cap5](https://user-images.githubusercontent.com/51368583/59662366-72a47780-91b5-11e9-9f03-54d872b8bef2.png)
<img width="934" alt="cap6" src="https://user-images.githubusercontent.com/51368583/59662380-7801c200-91b5-11e9-9dbe-3d2b84fc4a5d.png">
<img width="327" alt="cap7" src="https://user-images.githubusercontent.com/51368583/59662384-7afcb280-91b5-11e9-802a-cfac56b33ba1.png">
<img width="179" alt="cap8" src="https://user-images.githubusercontent.com/51368583/59662391-7e903980-91b5-11e9-98f6-9ef13ead96fc.png">
<img width="954" alt="cap9" src="https://user-images.githubusercontent.com/51368583/59662395-818b2a00-91b5-11e9-9037-5c91a7aceb43.png">
<img width="949" alt="cap10" src="https://user-images.githubusercontent.com/51368583/59662409-88b23800-91b5-11e9-81cd-b911bf2c7f97.png">
<img width="940" alt="cap11" src="https://user-images.githubusercontent.com/51368583/59662412-8b149200-91b5-11e9-811f-9fa60c37cc35.png">
<img width="944" alt="cap12" src="https://user-images.githubusercontent.com/51368583/59662417-8e0f8280-91b5-11e9-9796-8cd98c487c33.png">
<img width="937" alt="cap13" src="https://user-images.githubusercontent.com/51368583/59662426-91a30980-91b5-11e9-8d40-ed31440e0227.png">
<img width="943" alt="cap14" src="https://user-images.githubusercontent.com/51368583/59662433-949dfa00-91b5-11e9-8d18-affba25f4f24.png">
<img width="941" alt="cap15" src="https://user-images.githubusercontent.com/51368583/59662435-9667bd80-91b5-11e9-9886-a03750053404.png">
[zabbix_agentd.conf.txt](https://github.com/MantasTumenas/Zabbix-template-for-Microsoft-SQL-Server/files/3300332/zabbix_agentd.conf.txt)
[Zabbix_agentd.log](https://github.com/MantasTumenas/Zabbix-template-for-Microsoft-SQL-Server/files/3300333/Zabbix_agentd.log)
[Zabbix_agentd.log.old.txt](https://github.com/MantasTumenas/Zabbix-template-for-Microsoft-SQL-Server/files/3300334/Zabbix_agentd.log.old.txt)

Thanks in advance
Ioannis Pantelidis

**Comment by ioannis-pan** [comment]
<img width="335" alt="Capture" src="https://user-images.githubusercontent.com/51368583/59681166-ec4f5c00-91db-11e9-9d3c-fc866e8fc7f2.PNG">

Also as you can see there are multiple instances with a a lot of  {#DBNAME} , I don't know if it a issue.

**Comment by ioannis-pan** [comment]
i changed the number item limit of zabbix and also the i changed the "zabbix agent(active)" to "zabbix agent". Now **the items created**  but i am not sure if zabbix collecting any data. There are 1000+ items now on the host. I hope until tomorrow items will get the data.

**Comment by ioannis-pan** [comment]
Unfortunately, there are no data after creation of the items. Please advice.

**Comment by ioannis-pan** [comment]
Actually, i was forgotten to change the item prototypes too from active to passive. Now it is working great!

**Comment by MantasTumenas** [comment]
Ok, the way I see it, the issue was incorrectly configured or not configured zabbix and zabbix agent, to use active items. You found a workaround (changed all to passive). If it works for you - go ahead. Just remember, if you download a template again, you will have to change to passive type. Also, some items (log) works only as active type.

**Comment by gabovos** [comment]
Hi @ioannis-pan
 You did something special at the level of script or permissions so that the autodiscovery for the bbdd (databases.mssql.discovery) works for you, the discovery of the instances works for me, but at the database level it does not work for me. It brings me everything in white:
{ 
    "data":    [

                    ]
}

**Comment by MantasTumenas** [comment]
Have you assigned zabbix agent service rights to access your instance?

**Comment by gabovos** [comment]
No, I do not understand very well how I should give the services, is it a level of mssql, some user?

**Comment by MantasTumenas** [comment]
I have writen down in documentation which login and what rights must have.
Can you see it?

**Comment by MantasTumenas** [comment]
Hello,
Do you still have issues?
Mantas
