### ISSUE TITLE
database status items are unsupported

### ISSUE THREAD

**Issue by buckshome** [MantasTumenas/Zabbix-template-for-Microsoft-SQL-Server#23]
I installed the zabbix windows agent on the secondary server of an always on cluster.  Everything seems to be working except the database status zabbix items.  Zabbix says they are not supported for some reason.  All other triggers/items from the plugin are working properly.  I don't see anything in the logs.  I only have one instance with about 12 different databases.  It seems like the discovery scripts account for servers with only one instance.  I gave the SYSTEM user sysadmin access so that shouldn't be the problem.    I'm running zabbix 4.2  Any thoughts?  Maybe database status is only supported on primary server?

**Comment by MantasTumenas** [comment]
"I installed the zabbix windows agent on the secondary server of an always on cluster." - so on primary server database status is reported?
"Zabbix says they are not supported for some reason." - anything from zabbix error log? Have you tried debug level 5? Also "Not supported" in Discovery tab or Items tab?
"It seems like the discovery scripts account for servers with only one instance." - no, it discovers all instances and all databases.
"Maybe database status is only supported on primary server?" - no, it works on all servers. Personally have 6 instances with ~80 databases (AlwaysOn, log shipping, mirroring) per primary and per secondary serves. It creates performance issues, but database status is displayed correctly.
"Any thoughts?" - if "All other triggers/items from the plugin are working properly." on secondary server I assume zabbix item type active is configured correctly and it works. My troubleshooting map would be like this:

1. Execute T-SQL script part from Discovery.mssql.databasestatus.ps1 with corrected dbname values on the SQL server (via SSMS). If it works go to
2. Execute T-SQL script part from Discovery.mssql.databasestatus.ps1 with corrected dbname values AND as a Zabbix agent account (login) on the SQL server (via SSMS). If it works go to
3. Execute powershell script Discovery.mssql.databasestatus.ps1 locally on server via command console. Remember to provide correct instance name and database name (let's say 'master') as a parameters.

Let me know the results

**Comment by buckshome** [comment]
The performance stats all seem to be coming in fine.  Some of the powershell scripts are working and some are not.   Seems like all the scripts that pull names work and the ones that pull status values do not.  

![zabbix1](https://user-images.githubusercontent.com/30200081/63885154-bb429300-c9a5-11e9-84ce-ce74752779fe.png)
![zabbix2](https://user-images.githubusercontent.com/30200081/63885158-bed61a00-c9a5-11e9-99c5-a39712e9cfb3.png)

**Comment by buckshome** [comment]
Currently I only have the agent installed on the secondary server so I don't know if it will work on the primary.  The "not supported" label is in the items tab.  I'm also getting corresponding "unknown" states on the database status triggers.

**Comment by buckshome** [comment]
Seeing the same thing in the zabbix agent logs (debug level 5):

`  5948:20190828:174922.924 EXECUTE_STR() command:'powershell.exe -NoProfile -ExecutionPolicy Bypass -File "C:\zabbix\bin\Discovery.mssql.databasestatus.ps1" -instName "MSSQLSERVER" -dbName "msdb"' len:26 cmd_result:'Error executing quer'
  5948:20190828:174922.924 for key [database.mssql.status[MSSQLSERVER,msdb]] received value [Error executing query on !]
  5948:20190828:174922.925 In process_value() key:'thanos:database.mssql.status[MSSQLSERVER,msdb]' lastlogsize:null value:'Error executing query on !'`

**Comment by MantasTumenas** [comment]
From the info you provided I see that:

1. Databases names are queried successfully.
2. THANOS - what is this? A server (host) name?
3. 'Error executing query on !' - I saw this error, then the SELECT script failed for some reasons. Could you provide results for this solution - Execute T-SQL script part from Discovery.mssql.databasestatus.ps1 with corrected dbname values AND as a Zabbix agent account (login) on the SQL server (via SSMS).?

**Comment by buckshome** [comment]
I'm getting closer to solving this.  It definitely seems to be a powershell execution permission problem for the SYSTEM user that zabbix runs as.   If I add the SYSTEM user to the Administrators group on the server the database statuses are picked up perfectly fine.

**Comment by buckshome** [comment]
Oh, and I forgot to mention, the first problem I found was that the secondary server (which is what I'm testing this monitoring script on) was not set to read-only mode in SSMS.   Now, back to the powershell issue....

![SSMS](https://user-images.githubusercontent.com/30200081/64182588-7485ea80-ce36-11e9-93f2-854537ea17d2.png)

**Comment by MantasTumenas** [comment]
"If I add the SYSTEM user to the Administrators group on the server the database statuses are picked up perfectly fine." - on the OS server or you mean SQL server?

**Comment by buckshome** [comment]
on the OS server

**Comment by MantasTumenas** [comment]
From documentation "5.	Grant rights for Zabbix Agent service account. It needs read rights on tables msdb.dbo.sysjobhistory, msdb.dbo.sysjobs and msdb.dbo.log_shipping_monitor_secondary. By default, Zabbix Agent service account is NT AUTHORITY\SYSTEM which is already in SQL Server.
6.	If you need to monitor mirrored databases or databases in Always On, you will have to give Zabbix Agent’s service account (NT AUTHORITY\SYSTEM by default) sysadmin rights. More about it here." - have you done this?

**Comment by frerora** [comment]
I wanted to bolt on to this, rather than open a separate incident, as it may be related.

I'm using the template/scripts on around 30 servers; all but one are working perfectly, and it's left me scratching my head.

Everything is working on this single server, bar the database status.

If I run Discover.mssql.databasename.ps1, it returns nothing, whereas every other server I have does return something.

The Zabbix log is clean. I can only assume this is permissions-related, but this server is setup exactly the same as all the working ones.

Any ideas at all?
Thanks!

**Comment by MantasTumenas** [comment]
It looks like you said - permission related issue. If you run T-SQL script from Discover.mssql.databasename.ps1 directly on said SQL server - does it returns database name? Also, does Zabbix Agent service account has sysadmin rights on SQL server?

**Comment by starlessboi** [comment]
Hi
I have the same issue,
I added user SYSTEM to administrators group, but it is not working. the command I used is :
Add-LocalGroupMember -Group Administrators -Member SYSTEM
the windows is 2016
did I miss some thing?

**Comment by buckshome** [comment]
Hmm...All i had to do was give SYSTEM Administrator rights on the server and give SYSTEM sysadmin rights on the database.    I guess the better way to do it, is to create a zabbix agent service user and run the zabbix agent as that user.  Then add the user to the administrator's group on the server and add the user as a sysadmin user on the database.

**Comment by MantasTumenas** [comment]
> Hi
> I have the same issue,
> I added user SYSTEM to administrators group, but it is not working. the command I used is :
> Add-LocalGroupMember -Group Administrators -Member SYSTEM
> the windows is 2016
> did I miss some thing?

Have you given sysadmin rights for Zabbix agent service account in SQL server?

**Comment by MantasTumenas** [comment]
> I guess the better way to do it, is to create a zabbix agent service user and run the zabbix agent as that user. Then add the user to the administrator's group on the server and add the user as a sysadmin user on the database.

Looking from the security side it would be better, but remember most of the users do not create separate account for zabbix agent. Most go with the out-of-the-box solution. Documentation covers both cases:
_"5.	Grant rights for Zabbix Agent service account. It needs read rights on tables msdb.dbo.sysjobhistory, msdb.dbo.sysjobs and msdb.dbo.log_shipping_monitor_secondary. By default, Zabbix Agent service account is NT AUTHORITY\SYSTEM which is already in SQL Server."_

**Comment by MantasTumenas** [comment]
> Hmm...All i had to do was give SYSTEM Administrator rights on the server and give SYSTEM sysadmin rights on the database.

I believe this _"give SYSTEM sysadmin rights on the database"_ should have been enough. As it says in documentation
_"5.	Grant rights for Zabbix Agent service account. It needs read rights on tables msdb.dbo.sysjobhistory, msdb.dbo.sysjobs and msdb.dbo.log_shipping_monitor_secondary. By default, Zabbix Agent service account is NT AUTHORITY\SYSTEM which is already in SQL Server.
6.	If you need to monitor mirrored databases or databases in Always On, you will have to give Zabbix Agent’s service account (NT AUTHORITY\SYSTEM by default) sysadmin rights. More about it here."_

**Comment by krzysztof-sz** [comment]
I have NT AUTHORITY\SYSTEM with sysadmin and it doesn't work. I no longer have the strength to look for the reason for "Unsupported item key".
