### ISSUE TITLE
Database Items and DB metrics are not getting in Zabbix Dashboard 

### ISSUE THREAD

**Issue by harikrishnaroy** [MantasTumenas/Zabbix-template-for-Microsoft-SQL-Server#29]
Hi MantasTumenas,

I have imported the template i am able to see all the metrics of the SQL server but not the SQL database. What needs to be done to get the metrics of the databases in SQL server . Help will be much appreciated.

**Comment by MantasTumenas** [comment]
First idea - check if you have assigned sysadmin rights to zabbix agent
service account.

**Comment by harikrishnaroy** [comment]
@MantasTumenas Is it mandatory to provide sysadmin rights to zabbix agent
service account ?

**Comment by MantasTumenas** [comment]
No, it is not mandatory. In the manual I wrote to which tables zabbix agent
must have read rights. And under which circumstances sysadmin rights is a
must. Have you tried that?

**Comment by harikrishnaroy** [comment]
@MantasTumenas if we run the zabbix agent with local system will it work ? as we are facing this issue and unable to figure it out. Help very much appreciated.

**Comment by MantasTumenas** [comment]
Yes, it should work
Mantas

**Comment by harikrishnaroy** [comment]
Through we run with service account we are not getting any metrics of Sql Server Database. ld you please help us to get that.Help very much appreciated.

**Comment by MantasTumenas** [comment]
Ok, contact me via gmail. send skype invite or smthg, so I can connect to
that server and check

**Comment by MantasTumenas** [comment]
Or send error logs

**Comment by MantasTumenas** [comment]
Closed due to no response from reporter.
