### ISSUE TITLE
Future implementation? 

### ISSUE THREAD

**Issue by killmasta93** [MantasTumenas/Zabbix-template-for-Microsoft-SQL-Server#33]
Hi there,
Thank you for taking the time of this template, Was wondering two things

1) possible to add on the template the top 10 expensive queries? and the Data File I/O 
the picture is from what i see on SSMS on the activity monitor

![image](https://user-images.githubusercontent.com/13953629/90325813-069eda00-df46-11ea-9f0e-4a66520e23fb.png)

2) would be it possible to replicate to monitor on ubuntu server running linux mssql 2019?

Thank you

**Comment by MantasTumenas** [comment]
Hello,
"possible to add on the template the top 10 expensive queries?" - no. At
least I do not know how to do that. Also there are limitations on how many
symbols a zabbix item can hold in a latest data field. 255 symbols if I am
not mistaken. So any (expensive) query, usually is longer than 255 symbols.
"Data File I/O" - if it can be monitored via windows OS performance
counters, you can create by yourself. I will not create it on SQL template,
but I have created them on a separate Windows OS template.
[image: image.png]


"would be it possible to replicate to monitor on ubuntu server running
linux mssql 2019?" It is a highly requested feature, but I postponed it
till the Corona storm will pass. At the moment I do not have time or
resources to create and test it on the linux platform.

sincerely,
Mantas

**Comment by killmasta93** [comment]
Thanks for the reply, will keep that in mind, as for the mssql 2019 if you need the resources i can create you  VM and give you access, thank you again
