### ISSUE TITLE
How can I monitor the MS SQL Diskgroup free and used space?

### ISSUE THREAD

**Issue by absz1980** [MantasTumenas/Zabbix-template-for-Microsoft-SQL-Server#34]
Hello!
How can I monitor the MS SQL filegroup and file free and used space?
I found Log percent used only.

**Comment by MantasTumenas** [comment]
"Log percent used" parameter is taken from performance counters. There is
no such parameter for MSSQL file (as in data file - mdf, ndf), so to this,
you will have to create custom scripts
