### ISSUE TITLE
Jobs error not reported

### ISSUE THREAD

**Issue by johnmcchavs** [MantasTumenas/Zabbix-template-for-Microsoft-SQL-Server#35]
Hello,

I installed your template on several MSSQL servers. Warnings and erros seems to act fine (there are many problems coming from the agent concerning SQL so the template seems to work fine), but I can see that (some) job errors did not, and it is the main reason I use it.
Where should I look first, knowing that I an in no way a developper, and just started to work with zabbix?
Thank you very much for the work put on that project, and cheers from France.

Edit : looking more sharply, I can see that the triggers are not available. Maybe this server is too old (it is a MSSQL 2005) for the template to work fine. I'll read the documentation more and come back to you once I figured out the possible cause.

**Comment by MantasTumenas** [comment]
MS SQL 2005 is not supported with SQL agent jobs, because discovery is based on Powershell 3.0. Which is usually missing from servers with MSSQL 2005
