### ISSUE TITLE
data not coming in? 

### ISSUE THREAD

**Issue by killmasta93** [MantasTumenas/Zabbix-template-for-Microsoft-SQL-Server#36]
Hi,
Currently we have MSSQL 2016 standard, installed the zabbix agent then the powershell scripts. After that i put the role sysadmin to NT i only get alert for the backup but i dont see the information of mssql nor the agents? 

![image](https://user-images.githubusercontent.com/13953629/107173056-ea2fa780-6994-11eb-89da-4de6119f878b.png)
![image](https://user-images.githubusercontent.com/13953629/107173074-f451a600-6994-11eb-9d01-4913c768a698.png)
![image](https://user-images.githubusercontent.com/13953629/107173090-fc114a80-6994-11eb-94cd-f71f39c3320f.png)
![image](https://user-images.githubusercontent.com/13953629/107173125-0cc1c080-6995-11eb-9253-782a83277597.png)

Thank you

**Comment by MantasTumenas** [comment]
By the looks of Your pictures, I guess the problem is server language settings. One user faced similar problem 
"The problem was that the server i was trying to monitor wasn't in English, so every key of the active template didn't exists, i've translated everything with its proper keys and then it worked". When You go to Performance Monitor and select counters - do You see them in English?

**Comment by killmasta93** [comment]
thanks for the reply but whats odd is that i have another server also in Spanish and the info seems to be coming in also 
not sure if this the location of the counters 

![image](https://user-images.githubusercontent.com/13953629/107392444-af7a5c00-6ac7-11eb-97e8-6ffed7854152.png)


Thank you

**Comment by MantasTumenas** [comment]
The location of the counters can be checked here https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-rdsh-performance-counters
What language do you see here?

**Comment by killmasta93** [comment]
Thanks for the reply, it seems to be in spanish 
![image](https://user-images.githubusercontent.com/13953629/107729428-e36ba200-6cbe-11eb-97c2-174405c67f15.png)

is it possible to put the MSSQL into English?

**Comment by MantasTumenas** [comment]
"is it possible to put the MSSQL into English?" - I do not know of such possibilities. Shorter road would be: copy/paste current template and translate items from English to Spanish. Or translate from English to performance counters IDs (numeric value, same for all languages).

**Comment by killmasta93** [comment]
so i reinstalled it better now its working again
