### ISSUE TITLE
Backup Threshold? 

### ISSUE THREAD

**Issue by killmasta93** [MantasTumenas/Zabbix-template-for-Microsoft-SQL-Server#37]
Hi,
I was wondering if its possible to change the threshold on the backup its currently to check every 7 days for full
Thank you

**Comment by MantasTumenas** [comment]
Yes, You can change it. Go to template macros and look for {$UDBFTIME1} -
UserDBFullTime

**Comment by MantasTumenas** [comment]
Yes, You can change it. Go to template macros and look for {$UDBFTIME1} - UserDBFullTime

**Comment by killmasta93** [comment]
Thank for the reply, i tried changing  it but it still seems to show 7 days

![Screenshot_2021-06-04_10-38-49](https://user-images.githubusercontent.com/13953629/120827808-7015c680-c521-11eb-88bb-2437d0f3791e.png)
![Screenshot_2021-06-04_10-38-33](https://user-images.githubusercontent.com/13953629/120827810-7146f380-c521-11eb-91a0-121697e79fb1.png)

**Comment by killmasta93** [comment]
i stopped the backup to see if i get an alert and correct it did work
