### ISSUE TITLE
Key already Exists

### ISSUE THREAD

**Issue by bleckmeister** [MantasTumenas/Zabbix-template-for-Microsoft-SQL-Server#45]
hello, i have followed the instructions but it get the error below when i restart the zabbix agent

cannot load user parameters: user parameter "backup.sysdatabase.mssql.discovery,powershell.exe -NoProfile -ExecutionPolicy Bypass -File "C:\Program Files\Zabbix Agent\bin\MSSQL\DiscoveryDatabaseBackup\Discovery.mssql.sysdatabasename.ps1"": key "backup.sysdatabase.mssql.discovery" already exists

**Comment by farzadha2** [comment]
did you also give NT AUTHORITY\SYSTEM  as sysadmin permissions? thought the ssms?

**Comment by bleckmeister** [comment]
yes i have. NT AUTHORITY SYSTEM has sysadmin and public server roles.

**Comment by bleckmeister** [comment]
Well i fixed it by using *.conf instead of the triple. 

Include=C:\Program Files\Zabbix Agent\zabbix_agentd.d\*.conf
#Include=C:\Program Files\Zabbix Agent\zabbix_agentd.d\mssql.agent.userparams.conf
#Include=C:\Program Files\Zabbix Agent\zabbix_agentd.d\mssql.backup.userparams.conf
#Include=C:\Program Files\Zabbix Agent\zabbix_agentd.d\mssql.basic.userparams.conf
