### ISSUE TITLE
Discovery - Value should be a JSON object

### ISSUE THREAD

**Issue by FabianZimbalev** [MantasTumenas/Zabbix-template-for-Microsoft-SQL-Server#9]
Hello,

I followed the instructions and added the baseline template to one host.
Now when the discovery runs, it returns me the following message: Value should be a JSON object.
This happens for the SQL Server Database Discovery and for the SQL Server Instances Discovery.
Is there anything I´m missing in my configuration ?

**Comment by MantasTumenas** [comment]
Hi. Which win server version and which powershell version?
Mantas

**Comment by FabianZimbalev** [comment]
Powershell version 5.1
Win-Server 2016 Standard

Best regards

Fabian Zimbalev

**Comment by MantasTumenas** [comment]
Send me zabbix agent log and config file

**Comment by MantasTumenas** [comment]
Yesterday had a similar case wit  "Value should be a JSON object". Turns
out the path in user parameters was not correct - it did not point to
powershell scripts.
Mantas

**Comment by MantasTumenas** [comment]
Hi,
Please update on your situation. If you are still experience problem, I can
find a time to help you via teamviewer.
Mantas

**Comment by FabianZimbalev** [comment]
Hi Mantas,

I found the issue.
I wrote a litte ps file that would install Zabbix for me and download your files. Unfortunatly the stream did break and the the file download was not completed. 
When zabbix tried to run the Powershell Script, it returned some errors which are not JSON objects.
This issue is "fixed" and was not caused by your software.

Thanks.
Fabian

**Comment by romdudPL** [comment]
Hi Mantas,
I've installed your files to monitor two SQL server. One is working great, but the second has problem Discovery - Value should be a JSON object.
I'm not sure where to look for reason of that situation.
Problematic server is Win2008R2, Powershell 4.
I've run PS scripts on commandline and I receive similar answer. So where is the problem?
Regards
RD

**Comment by MantasTumenas** [comment]
Hi, RD,
"Value should be a JSON object" in discovery windows means the poweshell
script for some reasons cannot be executed correctly. You have run PS
script via commandline ant got the similar results. So we can for sure that
the problem is with powershell. How do you know that you have powershell 4?
What does this command show $PSVersionTable.PSVersion
https://stackoverflow.com/questions/1825585/determine-installed-powershell-version
mantas

**Comment by romdudPL** [comment]
thanks for your answer. In the meantime I've deleted my post, because "JSON returned home" ;-)
I was impatient. After an hour everything worked correctly.
thanks again
regards
RD

**Comment by MantasTumenas** [comment]
A, wonderfull. Good luck
